from __future__ import annotations
# ========== CẤU HÌNH CAMERA ==========

CAMERA_INDEX = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 20
USE_DSHOW_ON_WINDOWS = True
DETECTION_EVERY_N_FRAMES = 2

# ========== CẤU HÌNH CỬA SỔ HIỂN THỊ ==========
WINDOW_NAME = "Tram mat dat tich hop AI"
FULLSCREEN = True

# ========== ĐƯỜNG DẪN CÁC MODEL AI ==========
PERSON_MODEL_PATH = "Model/Person/yolov8s.pt"
POSE_MODEL_PATH = "Model/Pose/yolov8s-pose.pt"
POSTURE_MODEL_CANDIDATES = [
    "Model/Posture/weights/best.pt",
]
RESCUE_MODEL_CANDIDATES = [
    "Model/Rescue_v3/weights/best.pt",
    "Model/Rescue_v4/weights/best.pt",
    "Model/Rescue/weights/best.pt",
]
RESCUE_HIGH_CONF_THRESHOLD = 0.85
TRACKER_CONFIG = "bytetrack.yaml"

# ========== TRỌNG SỐ DUNG HỢP (LATE FUSION) ==========
POSTURE_MODEL_WEIGHT = 0.85   
POSE_POSTURE_WEIGHT = 0.15    
POSTURE_FUSION_MIN_CONFIDENCE = 0.50 
POSTURE_FUSION_MIN_MARGIN = 0.05      
VICTIM_FUSION_THRESHOLD = 0.85

SIMULATE_WHEN_MODEL_MISSING = False
FALLBACK_SYNTHETIC_FRAME = True
CAMERA_SIMULATE_DISCONNECT = False  # Bấm phím V để giả lập mất kết nối camera

# ========== NGƯỠNG DANGER SCORE VÀ POSTURE ==========
WARNING_THRESHOLD = 55
DANGER_THRESHOLD = 85
AUTO_SAVE_MIN_SCORE = 85
FOCUS_SWITCH_SCORE_MARGIN = 15
POSTURE_MODE = "detailed" 
POSTURE_CONFIRM_WINDOW_FRAMES = 10
POSTURE_LYING_CONFIRM_FRAMES = 2
POSTURE_UPRIGHT_CLEAR_FRAMES = 2
POSTURE_STANDING_CONFIRM_FRAMES = 3
POSTURE_SITTING_CONFIRM_FRAMES = 3
POSTURE_MAJORITY_THRESHOLD = 0.60
LYING_RATIO_THRESHOLD = 1.6
STANDING_RATIO_THRESHOLD = 1.65
LYING_KEYPOINT_RATIO_THRESHOLD = 1.30
CENTER_SMOOTHING_FRAMES = 8
CENTER_JITTER_THRESHOLD = 30
MOVING_THRESHOLD = 80
MOTION_WINDOW_SECONDS = 3
STILLNESS_SECONDS = 5
LONG_IMMOBILE_SECONDS = 20
IMMOBILE_MOTION_SCORE = 20
MIN_POSTURE_BBOX_SIZE = 35
POSTURE_LOW_CONFIDENCE = 0.35
DROP_TARGET_SECONDS = 5
AUTO_DANGER_LOG_COOLDOWN_SECONDS = 60
AUTO_DANGER_SCORE_DELTA = 15
AUTO_DANGER_SKIP_MESSAGE_SECONDS = 10

# ========== CỬ CHỈ TAY (GESTURE) ==========
HAND_RAISE_HOLD_SECONDS = 1.0
WAVING_WINDOW_SECONDS = 2.0
WAVING_MIN_ABOVE_RATIO = 0.7
WAVING_MIN_DIRECTION_CHANGES = 3
WRIST_MOVE_THRESHOLD = 0.15
GESTURE_HOLD_AFTER_DETECT_SECONDS = 2.0
HAND_RAISE_MARGIN_PIXELS = 40

# ========== VÙNG GIÁM SÁT ROI ==========
ROI_ENABLED = False
SHOW_ROI_IN_CLEAN_MODE = True
ROI_LABEL = "VUNG NGUY HIEM / DANGER ROI"
ROI_CONFIG_FILENAME = "roi_config.json"
ROI_POINTS: list[tuple[int, int]] = []
ROI_EDIT_MODE = False
SHOW_SKELETON = False
SHOW_CROSSHAIR = False
ROI_EDIT_POINTS: list[tuple[int, int]] = []
ROI_BASE_SCORE = 10
ROI_CONTEXT_BONUS_SCORE = 10
ROI_MAX_SCORE = 30
ROI_NORMAL_PERSON_SCORE_CAP = 20

# ========== THỜI TIẾT ONLINE ==========
WEATHER_ENABLED = True
WEATHER_PROVIDER = "open_meteo"
WEATHER_LOCATION_NAME = "Hà Nội"
WEATHER_LAT = 21.0285
WEATHER_LON = 105.8542
WEATHER_UPDATE_INTERVAL_SECONDS = 600
INTERNET_CHECK_INTERVAL_SECONDS = 45
INTERNET_CHECK_TIMEOUT_SECONDS = 1.0
WEATHER_HTTP_TIMEOUT_SECONDS = 4.0

SAVE_COOLDOWN_SECONDS = 10

# ========== REPLAY VIDEO TỰ ĐỘNG ==========
SAVE_REPLAY_VIDEO = True
REPLAY_PRE_SECONDS = 10
REPLAY_POST_SECONDS = 10
REPLAY_FPS = 20
REPLAY_CODEC = "mp4v"
REPLAY_FALLBACK_CODEC = "XVID"
REPLAY_MIN_VALID_BYTES = 10 * 1024
REPLAY_MIN_FRAMES = 20

GENERATE_REPORT_ON_EXIT = True

